### ISSUE TITLE
gcc required due to vmstat add_runtime_dependency 

### ISSUE THREAD

**Issue by jpcarey** [sensu-plugins/sensu-plugins-memory-checks#22]
the add_runtime_dependency for vmstat requires that the system this gem will be deployed to must have a gcc compiler in order to compile the vmstat binary.  This is an annoying dependency, and is required even if the vmstat package is available on the system.

https://github.com/sensu-plugins/sensu-plugins-memory-checks/blob/master/sensu-plugins-memory-checks.gemspec#L44

**Comment by analytically** [comment]
@mattyjones

**Comment by mattyjones** [comment]
@jpcarey @analytically   Sorry for the late response. I agree with it being a pia, and would be open to pulling it if a better solution is known otherwise I am not sure what the best course of action is.

**Comment by confiq** [comment]
It's kinda problematic dependency... 
Perhaps moving vmstat to different plugin might be right solution?

`apt-get install build-essential` in debian will enable installing memory-checks plugin...

**Comment by analytically** [comment]
I'll accept a PR removing the dependency and detailing the vmstat installation for check-ram.rb. Would it also be possible to add a check to check-ram.rb?

**Comment by majormoses** [comment]
@analytically sorry I must have missed the email. I have yet to find a better solution with a ruby implementation and I dont think we can get around that. What I suppose we could do is make it a development dependency, add a check to the plugin, and detail the unique install instructions...

**Comment by analytically** [comment]
Sounds good! And add explanation in CAPITAL in plugin description...

**Comment by majormoses** [comment]
https://github.com/sensu-plugins/sensu-plugins-memory-checks/pull/25

**Comment by majormoses** [comment]
@jpcarey let me know if the pr fixes your issue
