### ISSUE TITLE
Add instructions for how to install `vmstat` Ruby package in Sensu's Ruby

### ISSUE THREAD

**Issue by nhooey** [sensu-plugins/sensu-plugins-memory-checks#30]
Your changelog mentions that the Ruby `vmstat` package has been removed as a dependency, but there are no instructions on how to install it in Sensu.

With the new 1.0 release, I'm getting this error:

``` ruby
/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- vmstat (LoadError) from
/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require' from
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-memory-checks-1.0.2/bin/check-ram.rb:36:in `<top (required)>' from /opt/sensu/embedded/bin/check-ram.rb:22:in `load' from
/opt/sensu/embedded/bin/check-ram.rb:22:in `<main>' Sensu::Plugin::CLI: ["Not implemented! You should override Sensu::Plugin::CLI#run."] 
```

**Comment by eheydrick** [comment]
There's a note in the README about the vmstat dependency. https://github.com/sensu-plugins/sensu-plugins-memory-checks#installation. I will clarify the instructions.

You install the `vmstat` gem with `/opt/sensu/embedded/bin/gem install vmstat --no-ri --no-rdoc` or the equivalent in your config management.

**Comment by nhooey** [comment]
@eheydrick When I try to install, I get this error:

```
$ sudo -H /opt/sensu/embedded/bin/gem install --no-ri --no-rdoc vmstat
Fetching: vmstat-2.1.0.gem (100%)
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ rb_sysopen - /opt/sensu/.gem/ruby/2.3.0/cache/vmstat-2.1.0.gem
```

So it's complaining that `/opt/sensu/.gem` doesn't exist. If I create that directory, it works.

**Comment by eheydrick** [comment]
You need to be root to write into the sensu dir. Try it sudo'ing to root and not the sensu user.

```
$ sudo /opt/sensu/embedded/bin/gem install vmstat --no-rdoc --no-ri
Fetching: vmstat-2.1.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed vmstat-2.1.0
1 gem installed
```

**Comment by eheydrick** [comment]
I updated [the README](https://github.com/sensu-plugins/sensu-plugins-memory-checks/blob/master/README.md#installation) with instructions for installing the `vmstat` gem.
