### ISSUE TITLE
Suddenly getting error: "cannot load such file -- vmstat"

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [sensu-plugins/sensu-plugins-memory-checks#32]
I have a system which launches VMs and installs this sensu plugin, as well, as several others. I haven't launched any VMs for a while (2 or 3 weeks) and I started launching some yesterday, and noticed that on each machine check-ram.rb produces this stack trace:

```
Sensu::Plugin::CLI: ["Not implemented! You should override Sensu::Plugin::CLI#run."]
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- vmstat (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.9.1/gems/sensu-plugins-memory-checks-1.0.2/bin/check-ram.rb:36:in `<top (required)>'
    from /usr/local/bin/check-ram.rb:23:in `load'
    from /usr/local/bin/check-ram.rb:23:in `<main>'
```

The process which provisions these VMs will install these plugins from scratch on each VM so I imagine that the version running right now is not the same as it was a few weeks ago. The base image that the VM uses was updated but I don't think there was anything ruby/sensu-related in that set of updates.

The metrics-memory.rb plugin seems to be working fine, as well as all the sensu plugins.

Is there anything else I need to install/update/tweak to get this working again?

**Comment by eheydrick** [comment]
Hi @SolomonShorser-OICR, the 1.0.0 release of the plugin removed the vmstat runtime dependency so that the gem could be installed on systems that don't have compilers installed. Therefore you must install the `vmstat` gem as an extra step when installing this plugin. See [the README](https://github.com/sensu-plugins/sensu-plugins-memory-checks/blob/master/README.md#installation) for details.

**Comment by SolomonShorser-OICR** [comment]
Thanks, I must have missed that! I'll add that `vmstat` gem to the playbook to see if it helps.

**Comment by soichih** [comment]
We just got hit by this. Thank you for posting this issue / answer.

Fixed it by doing `sudo /opt/sensu/embedded/bin/gem install vmstat`
