### ISSUE TITLE
vmstat gem required ?

### ISSUE THREAD

**Issue by dmsimard** [sensu-plugins/sensu-plugins-memory-checks#33]
I didn't need to install the vmstat gem manually until now. Just installing this plugin worked by itself.

What changed ? Why can't the plugin installation pull the vmstat gem by itself if it is now required ?

**Comment by eheydrick** [comment]
Hi @dmsimard, the `vmstat` gem was removed as a dependency so the plugin installation doesn't fail if gcc isn't installed. Check out the [README](https://github.com/sensu-plugins/sensu-plugins-memory-checks#installation) for more info.

**Comment by dmsimard** [comment]
How does this make sense ? The plugin doesn't work if the vmstat gem isn't installed.
So, great, now you can install it if gcc isn't installed but it still won't work because vmstat is required.
