### ISSUE TITLE
Needs to be updated for dependency 'sensu-plugins' 1.3.0 ?

### ISSUE THREAD

**Issue by mnellemann** [sensu-plugins/sensu-plugins-memory-checks#36]
Hi,

My sensu-plugins gem was updated to latest version 1.3.0, making this plugins fail.
Could it be updated to support the updated dependency ?

`/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb:310:in`to_specs': Could not find 'sensu-plugin' (= 1.2.0) - did find: [sensu-plugin-1.3.0](Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/opt/sensu/embedded/lib/ruby/gems/2.3.0:/opt/sensu/.gem/ruby/2.3.0', execute `gem env` for more information
    from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1439:in `block in activate_dependencies'
    from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1428:in`each'
    from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1428:in `activate_dependencies'
    from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1410:in`activate'
    from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:279:in `block in activate_bin_path'
    from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:279:in`synchronize'
    from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:279:in `activate_bin_path'
    from /opt/sensu/embedded/bin/check-memory.rb:22:in`<main>'`

**Comment by cwjohnston** [comment]
Hi @mnellemann, I looked into this and it [appears that version 0.0.9 shipped with the updated dependency you described](https://github.com/sensu-plugins/sensu-plugins-memory-checks/blob/v0.0.9/sensu-plugins-memory-checks.gemspec#L43). 

Will you please take a look at what version you are running and let us know if you still see a problem with this dependency when using the most recent release?
