### ISSUE TITLE
vmstat gem installation path

### ISSUE THREAD

**Issue by jaykumar-jnpr** [sensu-plugins/sensu-plugins-memory-checks#39]
> Install vmstat gem into the path that sensu gems are expected to run from:
>      sudo /opt/sensu/embedded/bin/gem install vmstat --no-rdoc --no-ri

following above instruction, what is the expected destination this would install the gem file to?

I am able to install this gem as user "sensu", and gem installation destination is

> /opt/sensu/.gem/ruby/2.3.0/gems

But rest of sensu gem dependencies are at

> /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/

I am not too happy about dependencies spread across multiple locations...

**Comment by majormoses** [comment]
@jaykumar-jnpr unless you are disabling the embedded gems it should be installed in the context of the embedded gems.

**Comment by majormoses** [comment]
@eheydrick should we close this due to lack of response?

**Comment by eheydrick** [comment]
@jaykumar-jnpr the gems should be installed under /opt/sensu/embedded. You'll need to install them as the root user as that directory is owned by root by default. the sudo command you included should do it however if you are still having problems feel free to reopen this and include the full output.
