### ISSUE TITLE
no default values for warning and critical

### ISSUE THREAD

**Issue by 030** [sensu-plugins/sensu-plugins-memory-checks#41]
sudo -u sensu /etc/sensu/plugins/check-memory-percent.rb
MEM CRITICAL - system memory usage: 27%

Is seems that there are no default tresholds, e.g. -w 80 and -c 90

**Comment by 030** [comment]
Could version 1.0.3 be created?

**Comment by majormoses** [comment]
@030 ya there has been some lag I have opened #54 if you need 1.0.3 lets rename this to be release 1.0.3

**Comment by 030** [comment]
No need for 1.0.3. Creating a new version is fine by me.

**Comment by eheydrick** [comment]
2.0.0 has the default thresholds added.
