### ISSUE TITLE
Release 2.1.0

### ISSUE THREAD

**Issue by majormoses** [sensu-plugins/sensu-plugins-memory-checks#54]
There was a major release that includes some major changes but it looks like it was never actually released. Can we get a release please? @eheydrick

**Comment by majormoses** [comment]
the last release I see is 1.0.2 we should release 2.0.0 and 2.1.0

**Comment by eheydrick** [comment]
yes, we should release 2.0.0. will try to work on that tomorrow.

**Comment by majormoses** [comment]
@eheydrick ping

**Comment by majormoses** [comment]
@sstarcher can we get a release please?

**Comment by eheydrick** [comment]
Apologies for the delay, working on cutting a release.

**Comment by eheydrick** [comment]
2.0.0 has been released.
