### ISSUE TITLE
Units Clarification

### ISSUE THREAD

**Issue by uojiaku** [sensu-plugins/sensu-plugins-memory-checks#58]
Can anyone tell what units these metrics are in? For instance the '4356' from root used and the number after it.

[mesocool@blueserver bin]$ sudo ./metrics-disk-usage.rb
myserver.laptop.disk_usage.root.used 4356 1490035728
myserver.laptop.disk_usage.root.avail 25415 1490035728
myserver.laptop.disk_usage.root.used_percentage 15 1490035728
myserver.laptop.disk_usage.root.boot.used 221 1490035728
myserver.laptop.disk_usage.root.boot.avail 1693 1490035728
myserver.laptop.disk_usage.root.boot.used_percentage 12 1490035728
myserver.laptop.disk_usage.root.tmp.used 3 1490035728
myserver.laptop.disk_usage.root.tmp.avail 1849 1490035728
myserver.laptop.disk_usage.root.tmp.used_percentage 1 1490035728
myserver.laptop.disk_usage.root.var.used 722 1490035728
myserver.laptop.disk_usage.root.var.avail 2953 1490035728
myserver.laptop.disk_usage.root.var.used_percentage 20 1490035728
myserver.laptop.disk_usage.root.var.log.used 184 1490035728
myserver.laptop.disk_usage.root.var.log.avail 9047 1490035728
myserver.laptop.disk_usage.root.var.log.used_percentage 2 1490035728
myserver.laptop.disk_usage.root.var.log.audit.used 20 1490035728
myserver.laptop.disk_usage.root.var.log.audit.avail 3654 1490035728
myserver.laptop.disk_usage.root.var.log.audit.used_percentage 1 1490035728
myserver.laptop.disk_usage.root.disks.data304.used 46439 1490035728
myserver.laptop.disk_usage.root.disks.data304.avail 4253943 1490035728
myserver.laptop.disk_usage.root.disks.data304.used_percentage 2 1490035728
myserver.laptop.disk_usage.root.data.starfs1.used 197290 1490035728
myserver.laptop.disk_usage.root.data.starfs1.avail 705438 1490035728
myserver.laptop.disk_usage.root.data.starfs1.used_percentage 22 1490035728
myserver.laptop.disk_usage.root.data.fo.used 103321 1490035728
myserver.laptop.disk_usage.root.data.fo.avail 4795028 1490035728
myserver.laptop.disk_usage.root.data.fo.used_percentage 3 1490035728

**Comment by uojiaku** [comment]
I wanted to guess that the metrics were in kb but I want to be sure.

**Comment by GhostLyrics** [comment]
@uojiaku sorry to hear you're frustrated. We're working to have standardized READMEs, with clearer documentation (see: [example: sensu-plugins-nvidia](https://github.com/sensu-plugins/sensu-plugins-nvidia), [draft:sensu-plugin-doc-draft](https://github.com/GhostLyrics/sensu-plugin-doc-draft)), but it will take some time.

**Comment by GhostLyrics** [comment]
The number is the UNIX timestamp of the time the measurement was taken, you can see an example running `date +%s` in a terminal.

**Comment by uojiaku** [comment]
Thanks, so what measurement is the number to the left of the timestamp?

**Comment by GhostLyrics** [comment]
Hold on, you're in the wrong repository. xD

Your output is for **disk usage** but this is the **memory** repository. Now I know why I could not find it in the code. Yes, [it is Megabytes](https://github.com/sensu-plugins/sensu-plugins-disk-checks/blob/master/bin/metrics-disk-usage.rb#L97).

**Comment by uojiaku** [comment]
Oh sorry about that. But yeah thanks again. I tried to gem install that plugin above "sensu-plugins-nvidia", but I don't have the command 'sensu-install'.

**Comment by GhostLyrics** [comment]
https://sensuapp.org/docs/latest/reference/plugins.html#use-sensu-install-to-install-sensu-plugins

**Comment by majormoses** [comment]
closing per: https://github.com/sensu-plugins/sensu-plugins-memory-checks/issues/58#issuecomment-287876380
