### ISSUE TITLE
memory-check.sh thresholds should not default to zero

### ISSUE THREAD

**Issue by peter-halligan** [sensu-plugins/sensu-plugins-memory-checks#59]
As other check plugins within the repo have defaults which will send an alert. There should be a default for memory-check.sh or an error which prevents the check running without defined thresholds. The lack of thresholds will continue to show a healthy status until the system falls over. Even an arbitrary Threshold which will raise an alert seems better than none.

**Comment by majormoses** [comment]
@peter-halligan would you be willing to submit a pr for this?

**Comment by EslamElHusseiny** [comment]
I've addressed this issue in this [PR](https://github.com/sensu-plugins/sensu-plugins-memory-checks/pull/62)

**Comment by majormoses** [comment]
@EslamElHusseiny thanks I reviewed, some minor changes and it looks good

**Comment by majormoses** [comment]
fixed per #62
