### ISSUE TITLE
Error while executing script check-memory.rb

### ISSUE THREAD

**Issue by osho1278** [sensu-plugins/sensu-plugins-memory-checks#63]
I am getting  following error will executing 
[root@localhost bin]# /opt/sensu/embedded/bin/ruby check-memory.rb -w 700 -c 800

**/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-memory-checks-3.0.0/bin/check-memory.sh: line 44: [: missing `]'**

Its because there is no space on line 44 
Instead of ` [ -z "$WARN"] || [ -z "$CRIT" ]; then` it should be `if [ -z "$WARN" ] || [ -z "$CRIT" ]; then
`

**Comment by majormoses** [comment]
@osho278 thanks for the report, I have a hotfix that just needs to go through CI and a release cut which should be done shortly.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-memory-checks/versions/3.0.1
